### ISSUE TITLE
Ruby 2.2.3 openssl error to install native extensions

### ISSUE THREAD

**Issue by brunoadacosta** [sstephenson/ruby-build#826] opened 2015-11-12 13:51 UTC
./project.h:116:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>

**Comment by brunoadacosta** [comment] 2015-11-12 13:52
```
$ rbenv install --version
#=> ruby-build 20151028

$ $ brew list
ansible                 docker                  glew                    libpng                  mongodb                 postgresql              tmux
autoconf                docker-compose          glm                     libtiff                 nginx                   psgrep                  tree
automake                docker-machine          go                      libtool                 node                    rbenv                   unfs3
bash                    elixir                  gource                  libxml2                 openssl                 readline                unixodbc
bash-completion         erlang                  heroku-toolbelt         libxslt                 ossp-uuid               redis                   webp
bazaar                  fig                     icu4c                   libyaml                 pcre                    ruby-build              wget
boost                   freetype                imagemagick             luajit                  pg_upgrade_internal.log sdl2                    wxmac
cabal-install           gettext                 jpeg                    macvim                  phantomjs               sdl2_image              xz
cmake                   ghc                     libevent                memcached               pidof                   sysdig
cscope                  git                     libiconv                mercurial               pkg-config              the_silver_searcher

```

**Comment by papriwalprateek** [comment] 2015-11-12 14:00
+1

rbenv install 2.2.3 fails for me as well with the following error :-

```
ossl_ssl.c:141:27: error: 'SSLv3_method' undeclared here (not in a function)
     OSSL_SSL_METHOD_ENTRY(SSLv3),
                           ^
ossl_ssl.c:119:69: note: in definition of macro 'OSSL_SSL_METHOD_ENTRY'
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                     ^
ossl_ssl.c:142:27: error: 'SSLv3_server_method' undeclared here (not in a function)
     OSSL_SSL_METHOD_ENTRY(SSLv3_server),
                           ^
ossl_ssl.c:119:69: note: in definition of macro 'OSSL_SSL_METHOD_ENTRY'
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                     ^
ossl_ssl.c:143:27: error: 'SSLv3_client_method' undeclared here (not in a function)
     OSSL_SSL_METHOD_ENTRY(SSLv3_client),
                           ^
ossl_ssl.c:119:69: note: in definition of macro 'OSSL_SSL_METHOD_ENTRY'
 #define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
```

My ruby-build version - 
```
$ rbenv install --version
#=> ruby-build 20151028
```

**Comment by brunoadacosta** [comment] 2015-11-12 14:24
ruby 2.2.3 on my machine was installed

the problem with openssl occurs on eventmachine gem, i solve using this

gem install eventmachine -v '1.0.8' -- --with-cppflags=-I/usr/local/opt/openssl/include

**Comment by mislav** [comment] 2015-11-12 16:58
I would argue that this is a problem with eventmachine gem build process. It seems that Ruby was correctly installed and its openssl extension was linked to OpenSSL from Homebrew. Everything was fine, except that eventmachine wanted to link to openssl manually during its own build process (for some reason—I don't know why it didn't use Ruby's extension). You worked around your issue, but it doesn't change the fact that eventmachine's build process is not optimal.

**Comment by hsbt** [comment] 2015-11-12 23:11
I think you need to add ```--with-openssl-dir=`brew --prefix openssl```` like this.

```
$ CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 2.2.3
```

homebrew didn't create symlink into `/usr/local` directory.

**Comment by brunoadacosta** [comment] 2015-11-13 21:00
this only about 2.2.3. my 2.2.2 installation works fine, why?

**Comment by brunoadacosta** [comment] 2015-11-13 21:17
@hsbt does not work, same problem

**Comment by hsbt** [comment] 2015-11-13 22:24
I can reproduce Ruby 2.2.2 and 2.2.3. It's eventmachine or your environment issue.

```gem install eventmachine -v '1.0.8' -- --with-cppflags=-I`brew --prefix openssl`/include``` is correct instruction I think. It causes by homebrew mechanism .

**Comment by brunoadacosta** [comment] 2015-11-15 23:48
it's eventmachine issue !

**Comment by mislav** [comment] 2015-11-16 10:20
Closing since it's not our issue. Thanks for the investigation!

**Closed by mislav** 2015-11-16 10:20 UTC
