### ISSUE TITLE
Ruby 2.2.x builds experience segmentation fault

### ISSUE THREAD

**Issue by tdm00** [sstephenson/ruby-build#778] opened 2015-06-28 06:26 UTC
I'm not sure if this problem is with ruby-build installing Ruby 2.2.x or with the builds that are downloaded by ruby-build to install, although my guess is with the later. 

Using rbenv and ruby-build on my Mac 10.10.4 beta 2 I have installed Ruby 2.2.2 and run my application locally without issue.

On my production `Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-86-generic x86_64)` server I have 1.9.3-p385 running. I updated rbenv and ruby-build to the latest versions and then installed Ruby 2.2.2 which seems to have installed successfully. I'm able to enter irb and perform some basic commands without issue. I then deploy my rails application using Capistrano and during the asset:precompile Ruby experiences a segmentation fault at 0x00000000000000 with therubyracer gem.

After trying different versions of therubyracer I decided to try a different version of Ruby. I tried Ruby 2.2.0 and 2.2.1, both also experienced the segmentation fault at the same point during asset:precompile and with therubyracer. I then decided to go down another version and installed Ruby 2.1.6. This version now successfully completed the asset:precompile and runs without any segmentation faults.  
```
drwxr-xr-x  6 deployer sudo 4096 Jun 28 01:44 2.1.6/
drwxr-xr-x  6 deployer sudo 4096 Jun 28 01:18 2.2.2/
```

Now, even more curious to me is that I have a completely different Rails app running on a completely different `Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-86-generic x86_64)` server. This app also uses the same version of therubyracer. I installed Ruby 2.2.2 using ruby-build 24 hours earlier and this one does not experience a segmentation fault with therubyracer gem during the asset:precompile.

```
drwxr-xr-x  6 deployer sudo 4096 Feb 17  2013 1.9.3-p385/
drwxr-xr-x  6 deployer sudo 4096 Jul 12  2013 1.9.3-p448/
drwxr-xr-x  6 deployer sudo 4096 Jul 12  2013 2.0.0-p247/
drwxr-xr-x  6 deployer sudo 4096 Jan  2 14:40 2.1.5/
drwxr-xr-x  6 deployer sudo 4096 Jun 27 00:47 2.2.2/
```

The only other difference I have found between the first server and the second server, other than performing the installs 24 hours apart, is that I'm using a slightly different build of rbenv
```
First server (Ruby 2.2.2 works)
rbenv 0.4.0-129-g7e0e85b
ruby-build at commit 702b410e8d49408283d59450c50dfa63572fb99e

Second server (Ruby 2.x.x segfaults)
rbenv 0.4.0-151-g83ac0fb
ruby-build at commit 702b410e8d49408283d59450c50dfa63572fb99e
```

**Comment by mislav** [comment] 2015-06-29 19:54
Hi thanks for the detailed report.

First of all, the rbenv version doesn't matter much here. Rbenv just switches versions and can't cause segfaults.

This *could* theorietically be a problem with the way we compile Ruby through ruby-build, but I'm not convinced. Instead, I would rather bet on this being a problem with therubyracer. If that is so, I'm afraid we can't help you.

Is it an option that you remove therubyracer from your bundle and instead ensure that Node.js is preinstalled on the machines with run this application? In the long run, I think that solution is best for your assets needs.

**Comment by mislav** [comment] 2015-09-28 10:44
Closing because the problem is most likely with therubyracer. If you have new info, please reopen!

**Closed by mislav** 2015-09-28 10:44 UTC
