### ISSUE TITLE
Can't install when ruby version is given by `~/.rbenv/version`

### ISSUE THREAD

**Issue by phs** [sstephenson/ruby-build#814] opened 2015-10-22 22:40 UTC
It seems that when the ruby version is given by `~/.rbenv/version` and not `./.ruby-version`, `ruby-build` is no longer able to install the chosen version:

```bash
vagrant@vagrant:~/project$ rbenv global jruby-1.7.19
rbenv: version `jruby-1.7.19' not installed
vagrant@vagrant:~/project$ cat ~/.rbenv/version
jruby-1.7.19
vagrant@vagrant:~/project$ rbenv version
rbenv: version `jruby-1.7.19' is not installed (set by /home/vagrant/project/.ruby-version)
 (set by /home/vagrant/project/.ruby-version)
vagrant@vagrant:~/project$ cat ./.ruby-version
cat: ./.ruby-version: No such file or directory
vagrant@vagrant:~/project$ rbenv install
Usage: rbenv install [-f] [-kvp] <version>
       rbenv install [-f] [-kvp] <definition-file>
       rbenv install -l|--list

  -l/--list          List all available versions
  -f/--force         Install even if the version appears to be installed already
  -s/--skip-existing Skip if the version appears to be installed already

  ruby-build options:

  -k/--keep          Keep source tree in $RBENV_BUILD_ROOT after installation
                     (defaults to $RBENV_ROOT/sources)
  -v/--verbose       Verbose mode: print compilation status to stdout
  -p/--patch         Apply a patch from stdin before building

For detailed information on installing Ruby versions with
ruby-build, including a list of environment variables for adjusting
compilation, see: https://github.com/sstephenson/ruby-build#usage

vagrant@vagrant:~/project$ echo jruby-1.7.19 > ./.ruby-version
vagrant@vagrant:~/project$ rbenv install
Downloading jruby-bin-1.7.19.tar.gz...
^Cvagrant@vagrant:~/project$
vagrant@vagrant:~/project$
vagrant@vagrant:~/project$
vagrant@vagrant:~/project$ uname -a
Linux vagrant 3.2.0-29-virtual #46-Ubuntu SMP Fri Jul 27 17:23:50 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant:~/project$ cd ~/.rbenv/plugins/ruby-build
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ git log -1
commit d76bd0cba7026f3ffaa6cf39f0dd95b455990f46
Merge: 717a54c 4a1789f
Author: Mislav Marohnić <mislav.marohnic@gmail.com>
Date:   Thu Oct 22 11:42:08 2015 +0200

    Merge pull request #813 from etehtsea/jruby-9.0.3.0

    Add jruby-9.0.3.0
vagrant@vagrant:~/.rbenv/plugins/ruby-build$
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ rbenv --version
rbenv 0.4.0-169-g0f44c57
```

**Comment by phs** [comment] 2015-10-22 22:53
Actually, I notice putting it in `~vagrant/.ruby-version` doesn't work either.  Now I'm suspicious of the filesystem boundary occurring at `~/project`.

**Comment by phs** [comment] 2015-10-23 17:03
Ack, this is what I get for sticking together and scrubbing a session log.  Here's a new one that should hopefully be a little friendlier on the eyes (I can still reproduce).

First, demonstrate that my effective ruby version is coming only from global config, and that the selected version is not installed:

```
vagrant@vagrant:~/project$ rbenv global jruby-1.7.19
rbenv: version `jruby-1.7.19' not installed
vagrant@vagrant:~/project$ cat ~/.rbenv/version
jruby-1.7.19
vagrant@vagrant:~/project$ rbenv version
rbenv: version `jruby-1.7.19' is not installed (set by /home/vagrant/.rbenv/version)
 (set by /home/vagrant/.rbenv/version)
vagrant@vagrant:~/project$ cat ./.ruby-version
cat: ./.ruby-version: No such file or directory
```

Now try to install the configured version.  **Here's the bug**: instead of installing the version, I simply get the usage listing.

```
vagrant@vagrant:~/project$ rbenv install
Usage: rbenv install [-f] [-kvp] <version>
       rbenv install [-f] [-kvp] <definition-file>
       rbenv install -l|--list

  -l/--list          List all available versions
  -f/--force         Install even if the version appears to be installed already
  -s/--skip-existing Skip if the version appears to be installed already

  ruby-build options:

  -k/--keep          Keep source tree in $RBENV_BUILD_ROOT after installation
                     (defaults to $RBENV_ROOT/sources)
  -v/--verbose       Verbose mode: print compilation status to stdout
  -p/--patch         Apply a patch from stdin before building

For detailed information on installing Ruby versions with
ruby-build, including a list of environment variables for adjusting
compilation, see: https://github.com/sstephenson/ruby-build#usage
```

Now prove that if I put the same version in the local `./.ruby-version`, it works (or at least, works enough to start downloading, I can state it finishes and installs correctly.)

```
vagrant@vagrant:~/project$ echo jruby-1.7.19 > ./.ruby-version
vagrant@vagrant:~/project$ rbenv install
Downloading jruby-bin-1.7.19.tar.gz...
^Cvagrant@vagrant:~/project$
```

Finally, some relevant version numbers.

```
vagrant@vagrant:~/project$ uname -a
Linux vagrant 3.2.0-29-virtual #46-Ubuntu SMP Fri Jul 27 17:23:50 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant:~/project$ cd ~/.rbenv/plugins/ruby-build
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ git log -1
commit d76bd0cba7026f3ffaa6cf39f0dd95b455990f46
Merge: 717a54c 4a1789f
Author: Mislav Marohnić <mislav.marohnic@gmail.com>
Date:   Thu Oct 22 11:42:08 2015 +0200

    Merge pull request #813 from etehtsea/jruby-9.0.3.0

    Add jruby-9.0.3.0
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ rbenv --version
rbenv 0.4.0-169-g0f44c57
vagrant@vagrant:~/.rbenv/plugins/ruby-build$
```

In my second comment I noted that putting the version in `~vagrant/.ruby-version` (which is odd, but legal) _also_ does not work, despite being on the search path from the project dir to the filesystem root.  

From this I conjecture that the issue is somehow related to the details of my particular filesystem layout, and not the global mode intrinsically.  Particularly the image is obviously a vagrant box, and I have soft-linked `~/project` to `/vagrant`, which is on a different filesystem (the vagrant shared FS) than the root FS.

**Comment by mislav** [comment] 2015-10-24 05:29
I see now. I'm afraid you've hit up on expected behavior. For you see, `rbenv install` will [only attempt to install a locally specified version](https://github.com/sstephenson/ruby-build/blob/d76bd0cba7026f3ffaa6cf39f0dd95b455990f46/bin/rbenv-install#L107-113) (i.e. `.ruby-version`) if it's missing. However if the global version is missing, it won't attempt to install it.

That behavior makes sense to me. After all, you might often `cd` into a new project which specifies a Ruby version that you haven't installed. Then you can just use `rbenv install` to quickly obtain it. 

However, the same behavior doesn't make sense for global version. You are not allowed to set a global version to one that you haven't got installed, so I'm not sure how you ended up with "jruby-1.7.19" as the global version in the first place. Because the global version shouldn't change often, and is subject to your own choice rather than being some arbitrary configuration from a project, you are expected to install the version you want to use as global explicitly, rather than implicitly with `rbenv install` without arguments.

Does that make sense? Sorry, it's 7am for me and I haven't slept 😪

**Comment by phs** [comment] 2015-10-24 20:27
I suppose I can see the reason behind not attempting to install the global version, but I still think there's a bug here.  Particularly, if we take the global version off the table and instead use a `~/.ruby-version` (so, a "local" version simply higher up in the file system) then we still get this behavior.

**Comment by mislav** [comment] 2015-10-25 12:11
> Particularly, if we take the global version off the table and instead use a `~/.ruby-version` (so, a "local" version simply higher up in the file system) then we still get this behavior.

Which behavior is that? I'm afraid I didn't follow. If a `.ruby-version` file in current directory acts differently than a `.ruby-version` further up in the ancestry chain, that's a bug. But you'll have to give me more clearer info about that (e.g. what you did, what you expected, what happened instead)

**Comment by phs** [comment] 2015-10-25 18:48
Again, the problematic behavior is that ruby-build will not install the configured version, but simply show the usage message.  Let me exercise it again, now without any mention of the global version:

First, demonstrate that rbenv is pulling the ruby version from a `.ruby-version` file in the user's home (while the working directory is `~/project`.)  Cat the files just to be sure.

```
vagrant@vagrant:~/project$ rbenv version
rbenv: version `jruby-1.7.19' is not installed (set by /home/vagrant/.ruby-version)
 (set by /home/vagrant/.ruby-version)
vagrant@vagrant:~/project$ cat ~/.ruby-version
jruby-1.7.19
vagrant@vagrant:~/project$ cat ./.ruby-version
cat: ./.ruby-version: No such file or directory
```

*Exercise the bug*: Here I would expect `rbenv install` to install the chosen version.  Instead we get the usage.  Notice that since we're in `~/project`, `~/.ruby-version` is in a parent directory.

```
vagrant@vagrant:~/project$ rbenv install
Usage: rbenv install [-f] [-kvp] <version>
       rbenv install [-f] [-kvp] <definition-file>
       rbenv install -l|--list

  -l/--list          List all available versions
  -f/--force         Install even if the version appears to be installed already
  -s/--skip-existing Skip if the version appears to be installed already

  ruby-build options:

  -k/--keep          Keep source tree in $RBENV_BUILD_ROOT after installation
                     (defaults to $RBENV_ROOT/sources)
  -v/--verbose       Verbose mode: print compilation status to stdout
  -p/--patch         Apply a patch from stdin before building

For detailed information on installing Ruby versions with
ruby-build, including a list of environment variables for adjusting
compilation, see: https://github.com/sstephenson/ruby-build#usage
```

Prove that the bug vanishes if we move `~/.ruby-version` down one into the current directory.  Here I interrupt the install process after showing it at least knows what tarball to download.

```
vagrant@vagrant:~/project$ mv ~/.ruby-version ./
vagrant@vagrant:~/project$ rbenv install
Downloading jruby-bin-1.7.19.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/8e34f8a94bb6abedc0f6f9d0cc174b4fadc78a50fb44804c16f19bf8f2586d5d
^Cvagrant@vagrant:~/project$
```

Finally get some versions and shas.

```
vagrant@vagrant:~/project$ cd ~/.rbenv/plugins/ruby-build
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ git log -1
commit d76bd0cba7026f3ffaa6cf39f0dd95b455990f46
Merge: 717a54c 4a1789f
Author: Mislav Marohnić <mislav.marohnic@gmail.com>
Date:   Thu Oct 22 11:42:08 2015 +0200

    Merge pull request #813 from etehtsea/jruby-9.0.3.0

    Add jruby-9.0.3.0
vagrant@vagrant:~/.rbenv/plugins/ruby-build$ rbenv --version
rbenv 0.4.0-169-g0f44c57
```

**Comment by phs** [comment] 2015-10-25 19:01
I should quickly admit that my environment has an interesting mix of filesystems and symlinks.  I would be surprised if you could reproduce this directly.

As mentioned before, `~/project` is a symlink to `/vagrant`.  My belief is that `ruby-build` is searching up parent directories using it's own slightly-naive implementation, rather than the one in `rbenv` (which seemingly knows how to handle this corner case.)

**Comment by mislav** [comment] 2015-10-25 23:35
Thanks for the added info. Ruby-build simply uses `rbenv local` command. What is the output of that command in your cases?

**Comment by phs** [comment] 2015-10-26 01:12
That's interesting, `rbenv local` isn't finding the version, even though `rbenv version` does:

As before:

```
vagrant@vagrant:~/project$ rbenv version
rbenv: version `jruby-1.7.19' is not installed (set by /home/vagrant/.ruby-version)
 (set by /home/vagrant/.ruby-version)
vagrant@vagrant:~/project$ cat ~/.ruby-version
jruby-1.7.19
vagrant@vagrant:~/project$ cat ./.ruby-version
cat: ./.ruby-version: No such file or directory
```

And the kicker:

```
vagrant@vagrant:~/project$ rbenv local
rbenv: no local version configured for this directory
```

It seems this is actually an rbenv bug.

**Comment by mislav** [comment] 2015-10-26 08:30
So `rbenv local` only seems to look at `.ruby-version` [from the current directory](https://github.com/sstephenson/rbenv/blob/074161f9c122db659f513e30298dffd74f5ca1b0/libexec/rbenv-local#L50-L53).

That was by design, but I wonder if that design has a flaw, and needs to be fixed? Anyway, could you close this and open an issue in rbenv? Thanks

**Closed** 2015-10-27 18:31 UTC
