### ISSUE TITLE
ruby 2.1.1 fails to install on OSX 10.11

### ISSUE THREAD

**Issue by HParker** [sstephenson/ruby-build#809] opened 2015-10-04 03:33 UTC
Might be related to #797 or some of the permission changes in OSX 10.11

```
rbenv install 2.1.1
Downloading ruby-2.1.1.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/c843df31ae88ed49f5393142b02b9a9f5a6557453805fd489a76fbafeae88941
Installing ruby-2.1.1...

BUILD FAILED (OS X 10.11 using ruby-build 20150928)

Inspect or clean up the working tree at /var/folders/79/v_21t0xj00n_xfw79dd9bbsr0000gp/T/ruby-build.20151003212644.57498
Results logged to /var/folders/79/v_21t0xj00n_xfw79dd9bbsr0000gp/T/ruby-build.20151003212644.57498.log

Last 10 log lines:
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... yes
checking whether LDFLAGS is valid... no
configure: error: something wrong with LDFLAGS="-L/Users/adam/.rbenv/versions/2.1.1/lib "
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by hsbt** [comment] 2015-10-05 00:38
It's not related with #797 Can you try with Ruby 2.1.7?

**Comment by HParker** [comment] 2015-10-05 00:53
@hsbt 2.1.7 installs fine.
```
Downloading ruby-2.1.7.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/f59c1596ac39cc7e60126e7d3698c19f482f04060674fdfe0124e1752ba6dd81
Installing ruby-2.1.7...
Installed ruby-2.1.7 to /Users/adam/.rbenv/versions/2.1.7
```

**Comment by mislav** [comment] 2015-10-05 12:49
Thanks for reporting. This sounds like a duplicate of https://github.com/sstephenson/ruby-build/issues/798#issuecomment-130908433. If you have any extra information, can you add it to that thread? Thanks!

**Closed by mislav** 2015-10-05 12:49 UTC

**Comment by HParker** [comment] 2015-10-05 15:26
Thank you, I missed the duplicate.
